kind: Secret
apiVersion: v1
metadata:
  name: snl-secret
  namespace: snl
type: Opaque
data:
  GoogleClientID: # base64 encoded google client id
  GoogleClientSecret: # base64 encoded google client secret
  GoogleRedirectURL: # base64 encoded google redirect url
  MongoURI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby0wLm1vbmdvLnNubC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNw== # mongodb://root:example@mongo-0.mongo.snl.svc.cluster.local:27017
  RedisAddr: cmVkaXMtc2VydmljZS5zbmwuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ== # redis-service.snl.svc.cluster.local:6379
  RedisPassword: ""