apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: snl
spec:
  clusterIP: None   # Headless service, no external access
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017